#:schema node_modules/wrangler/config-schema.json
name = "workers-assets-test-hono"
main = "src/index.ts"
compatibility_date = "2024-09-03"
experimental_assets = { directory = "public", binding = "ASSETS" }
